- name: disable nginx module
  ansible.builtin.command: "dnf module disable nginx -y"

- name: enable nginx 1.24 
  ansible.builtin.command: "dnf module enable nginx:1.24 -y"

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: enable & start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove default nginx content
  ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download frontend content
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: unzip the frontend conent to /usr/share/nginx/html directory
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: copy nginx.conf to /etc/nginx/
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart nginx