- name: Installing mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Enabling and starting mysql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Changing the default root password 
  ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"